name: Feature Request for the blog
description: Make a feature request and help to improve the blog
title: "[Feature]: "
labels: [enhancement]
assignees:
- im-coder-lg

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request!

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: "A detailed and clear concise description of the bug:"
    placeholder: "Bug description:"
    value: "What happened in the bug:"
  validations:
    required: true
- type: textarea
  id: expectations
  attributes:
    label: What did you expect to happen?
    description: "A detailed and concise description of what you expected to happen:"
    placeholder: "What you expected to happen:"
    value: "Eg: Expected to see this..."
  
- type: dropdown
  id: npm-version
  attributes:
    label: Version
    description: "What version of NPM and Codedoc CLI are you running?"
    options:
    - 0.2.8 with NPM 6.14.4
    - 0.2.8 with NPM 7+
  validations:
    required: true
- type: textarea
  attributes:
    label: Console logs
    description: |
      "When you ran the app in the console, you got some logs, right? Post them here so that I can decipher the error."
