name: Bug Report
description: Create a bug report to help improve Google Assistant Unofficial Desktop Client 
labels: [bug]
assignees: im-coder-lg
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: blog-id
    attributes:
      label: The blog's special identification code
      description: Which blog has the problem?
      placeholder: v1.0.0-rc.2
    validations:
      required: true
  - type: input
    attributes:
      label: Local test and version of NPM
      description: Have you tested it locally and what version of NPM are you using?
      placeholder: e.g. Yes/No and NPM 7.2.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, screenshots) relevant to this bug.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
